nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes:
    - ./opt/htdocs:/opt/htdocs
    - ./opt/log/nginx:/opt/log/nginx

php:
  build: ./php
  ports:
    - "9000:9000"
  links:
    - "mysql"
  volumes:
    - ./opt/htdocs:/opt/htdocs

mysql:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./opt/data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
